/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-07-19 12:29:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.userBoard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/userBoard/Footer.jsp", Long.valueOf(1658231518351L));
    _jspx_dependants.put("/userBoard/Header.jsp", Long.valueOf(1658231513946L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<meta name=\"viewport\" content=\"width-device-width, initial-scale=1.0\">\r\n");
      out.write("	<title>유저 게시판</title>\r\n");
      out.write("	<link href=\"boardList.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("	<meta charset=\"UTF-8\">\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("	<link rel =\"stylesheet\" href=\"HeaderFooter.css\" type=\"text/css\"/>\n");
      out.write("	<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\n");
      out.write("	<script src=\"https://use.fontawesome.com/releases/v6.1.1/js/all.js\"></script>\n");
      out.write("	<title>헤더</title>\n");
      out.write("	<script>\n");
      out.write("		function showMenu(){\n");
      out.write("			if($(\".myMenu\").css(\"display\")==\"none\"){\n");
      out.write("				$(\".myMenu\").css(\"display\",\"block\")\n");
      out.write("			}else{\n");
      out.write("				$(\".myMenu\").css(\"display\",\"none\")\n");
      out.write("			}\n");
      out.write("		}\n");
      out.write("	</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<div class=\"HeaderContainer\">\n");
      out.write("		<div class=\"HeaderLogo\">\n");
      out.write("			<img src=\"../img/hugo_white_repair.jpeg\" style=\"width:100%; height:100%;\">\n");
      out.write("		</div>\n");
      out.write("		<div class=\"search\">\n");
      out.write("			<input type=\"text\" class=\"searchbox\"/>\n");
      out.write("			<button class=\"searchBtn\"><i class=\"fa-solid fa-magnifying-glass\"></i></button>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"headerMenu\">\n");
      out.write("			<a>이벤트/쿠폰</a>&nbsp;&nbsp;|&nbsp;&nbsp;\n");
      out.write("			<a>게시판</a>&nbsp;&nbsp;|&nbsp;&nbsp;\n");
      out.write("			<a>고객센터</a>&nbsp;&nbsp;|&nbsp;&nbsp;\n");
      out.write("			<a>로그인</a>&nbsp;&nbsp;|&nbsp;&nbsp;\n");
      out.write("			<a onclick=\"return showMenu()\"><i class=\"fa-solid fa-chalkboard-user\" class=\"user_info\"></i></a>\n");
      out.write("			<div class=\"myMenu\">\n");
      out.write("				<ul>	\n");
      out.write("					<li>ezen님</li>\n");
      out.write("					<li>&nbsp;</li>\n");
      out.write("					<li><a>회원정보</a></li>\n");
      out.write("					<li><a>쿠폰함</a></li>\n");
      out.write("					<li><a>찜리스트</a></li>\n");
      out.write("			</ul>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"serchDTL\">\n");
      out.write("			<button class=\"searchDTLBTN\">세부검색</button>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	<div id=\"wholeContainer\">\r\n");
      out.write("		<div class=\"side\"></div>\r\n");
      out.write("	\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div>\r\n");
      out.write("				<h2 style=\"color: #9bb7d6;\" >유저 게시판</h2>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"topContent\">\r\n");
      out.write("				<div class=\"leftRight\">\r\n");
      out.write("			 		<h2>오늘의 화제</h2>\r\n");
      out.write("			 		<ul>\r\n");
      out.write("			 			<li>ㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇ</li>\r\n");
      out.write("			 			<li>ㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇ</li>\r\n");
      out.write("			 			<li>ㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇ</li>\r\n");
      out.write("			 			<li>ㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇ</li>\r\n");
      out.write("			 			<li>ㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇ</li>\r\n");
      out.write("			 		</ul>\r\n");
      out.write("			 	</div>\r\n");
      out.write("			 	\r\n");
      out.write("			 	<div class=\"leftRight\">\r\n");
      out.write("			 		<h2>답변이 필요해요</h2>\r\n");
      out.write("			 		<ul>\r\n");
      out.write("			 			<li>ㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇ</li>\r\n");
      out.write("			 			<li>ㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇ</li>\r\n");
      out.write("			 			<li>ㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇ</li>\r\n");
      out.write("			 			<li>ㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇ</li>\r\n");
      out.write("			 			<li>ㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇ</li>\r\n");
      out.write("			 		</ul>\r\n");
      out.write("			 	</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"cateArea\">\r\n");
      out.write("				<div id=\"cate\">\r\n");
      out.write("		 			<a>전체</a>\r\n");
      out.write("		 			<a>맛집</a>\r\n");
      out.write("		 			<a>명소</a>\r\n");
      out.write("		 			<a>축제</a>\r\n");
      out.write("		 		</div>\r\n");
      out.write("		 			\r\n");
      out.write("		 		<div id=\"search\">\r\n");
      out.write("		 			<select>\r\n");
      out.write("		 				<option selected>제목</option>\r\n");
      out.write("		 				<option value=\"내용\">내용</option>\r\n");
      out.write("		 			</select>\r\n");
      out.write("		 			<input type=\"text\">\r\n");
      out.write("		 			<button type=\"submit\">검색</button>\r\n");
      out.write("		 		</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"sort\">\r\n");
      out.write("				<form>\r\n");
      out.write("					<input type=\"radio\" name=\"sort\" value=\"추천\">추천\r\n");
      out.write("					<input type=\"radio\" name=\"sort\" value=\"최신\">최신\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"boardList\">\r\n");
      out.write("				<table>\r\n");
      out.write("					<colgroup>\r\n");
      out.write("						<col style=\"width: 8%\">\r\n");
      out.write("						<col style=\"width: 52%\">\r\n");
      out.write("						<col style=\"width: 16%\">\r\n");
      out.write("						<col style=\"width: 8%\">\r\n");
      out.write("						<col style=\"width: 8%\">\r\n");
      out.write("						<col style=\"width: 8%\">\r\n");
      out.write("					</colgroup>\r\n");
      out.write("					<thead>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th>번호</th>\r\n");
      out.write("							<th>제목</th>\r\n");
      out.write("							<th>글쓴이</th>\r\n");
      out.write("							<th>등록일</th>\r\n");
      out.write("							<th>조회수</th>\r\n");
      out.write("							<th>추천수</th>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</thead>\r\n");
      out.write("					<tbody>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td class=\"cen\">ㅇ</td>\r\n");
      out.write("							<td>ㅇ</td>\r\n");
      out.write("							<td class=\"cen\">ㅇ</td>\r\n");
      out.write("							<td class=\"cen\">ㅇ</td>\r\n");
      out.write("							<td class=\"cen\">ㅇ</td>\r\n");
      out.write("							<td class=\"cen\">ㅇ</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						\r\n");
      out.write("					</tbody>\r\n");
      out.write("				</table>\r\n");
      out.write("			</div>\r\n");
      out.write("			<br/>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"postArea\">\r\n");
      out.write("				<input type=\"button\" value=\"글쓰기\" onclick=\"location.href='boardWrite.jsp'\" />\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"boardBottom\">\r\n");
      out.write("				<ul id=\"paging\">\r\n");
      out.write("					<li>이전</li>\r\n");
      out.write("					<li>&lt;</li>\r\n");
      out.write("					<li>1</li>\r\n");
      out.write("					<li>2</li>\r\n");
      out.write("					<li>3</li>\r\n");
      out.write("					<li>4</li>\r\n");
      out.write("					<li>5</li>\r\n");
      out.write("					<li>&gt;</li>\r\n");
      out.write("					<li>다음</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("		</div>\r\n");
      out.write("	\r\n");
      out.write("		<div class=\"side\"></div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<br/>\r\n");
      out.write("	");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("	<head>\n");
      out.write("	<meta charset=\"UTF-8\">\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\">\n");
      out.write("	<title>Footer</title>\n");
      out.write("	<link rel =\"stylesheet\" href=\"HeaderFooter.css\" type=\"text/css\"/>\n");
      out.write("	</head>\n");
      out.write("<body>										\n");
      out.write("   <div class=\"footer\">\n");
      out.write("   	 \n");
      out.write("   	 <div class=\"select\" >\n");
      out.write("   	 	<img src=\"../img/hugo_white.png\" width=\"70\" height=\"70\">&nbsp;&nbsp;\n");
      out.write("		<a href=''>회사소개</a> |\n");
      out.write("		<a href=''>개인정보처리방침</a> |\n");
      out.write("		<a href=''>서비스약관</a>\n");
      out.write("	 </div>\n");
      out.write("	 <div class=\"info\">\n");
      out.write("	 	<p>**회사</p>\n");
      out.write("	 	<p>서울특별시 서초구 서초대로77길 54 (서초더블유타워 13,14층)</p>\n");
      out.write("	 	<p>대표자:***</p>\n");
      out.write("	 	<p>사업자등록번호:1234567890</p>\n");
      out.write("	 	<p>T. 02 - 1234 - 5678</p>\n");
      out.write("	 \n");
      out.write("	 </div>\n");
      out.write("   </div>\n");
      out.write("  \n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
