-- CREATE TABLE

DROP TABLE EZEN.TB_DEPT_temp purge;
CREATE TABLE EZEN.TB_DEPT_temp(
	DEPT_CD CHAR(6) NOT NULL
	,DEPT_NM VARCHAR2(150) NOT NULL
	,UPPER_DEPT_CD CHAR(6)
);

ALTER TABLE EZEN.TB_DEPT_temp ADD CONSTRAINT PK_TB_DEPT_temp PRIMARY KEY (DEPT_CD);

DROP TABLE EZEN.TB_EMP_temp purge;
CREATE TABLE EZEN.TB_EMP_temp(
	EMP_NO 				CHAR(10) NOT NULL
	,EMP_NAME 			VARCHAR2(150) NOT NULL
	,BIRTH_DE 			CHAR(8) NOT NULL
	,LUNAR_YN			CHAR(1) NOT NULL
	,SEX_CD 			CHAR(3) NOT NULL
	,ADDR 				VARCHAR2(1000) NOT NULL
	,TEL_NO 			CHAR(150) NOT NULL
	,FINAL_EDU_SE_CD 	CHAR(3) NOT NULL
	,SAL_TRANS_BANK_CD 	CHAR(3) NOT NULL
	,SAL_TRANS_ACCNT_NO VARCHAR2(20) NOT NULL
	,DIRECT_MANAGER_EMP_NO CHAR(10)
	,DEPT_CD 			CHAR(6) NOT NULL
);

ALTER TABLE EZEN.TB_EMP_temp ADD CONSTRAINT PK_TB_EMP_temp PRIMARY KEY (EMP_NO);
ALTER TABLE EZEN.TB_EMP_temp ADD CONSTRAINT FK_TB_EMP_temp_01 FOREIGN KEY (DEPT_CD) REFERENCES EZEN.TB_DEPT_temp(DEPT_CD);


-- 컬럼 추가
-- 테이블의 마지막 컬럼이 되며 컬럼의 위치를 지정할 수는 없음
ALTER TABLE EZEN.TB_EMP_temp ADD (MARRIED_YN CHAR(1));

-- 컬럼 삭제
-- 한번 삭제된 컬럼은 복구 불가
ALTER TABLE EZEN.TB_EMP_temp DROP COLUMN MARRIED_YN;

-- 컬럼 수정
-- 컬럼의 크리글 늘릴 수는 있지만 줄일 수는 없음
-- NULL값만 가지고 있거나 아무 행도 없으면 줄일 수 있음
-- NOVALIDATE	: DEFAULT 값을 바꾸면 변경 작업 이후 발생하는 행 삽입에만 영향을 미침
ALTER TABLE EZEN.TB_EMP_temp
	MODIFY(MARRIED_YN CHAR(1) DEFAULT 'N' NOT NULL NOVALIDATE);

ALTER TABLE EZEN.TB_EMP_temp
	MODIFY(MARRIED_YN CHAR(1) DEFAULT 'N' NOT NULL);


-- 컬럼 수정 (RENAME) - Oracle 등 일부 DBMS에서만 지원
CREATE TABLE EZEN.TB_EMP_TEMP_2
AS SELECT * FROM EZEN.TB_EMP_TEMP tet ;

ALTER TABLE EZEN.TB_EMP_TEMP_2
RENAME COLUMN TEL_NO TO PHONE_NO;

ALTER TABLE EZEN.TB_EMP_TEMP_2
RENAME COLUMN PHONE_NO TO TEL_NO;


-- 제약조건 삭제
ALTER TABLE EZEN.TB_EMP_TEMP DROP CONSTRAINT FK_TB_EMP_TEMP_01;

-- 제약조건 추가
ALTER TABLE EZEN.TB_EMP_TEMP ADD CONSTRAINT FK_TB_EMP_TEMP_01
FOREIGN KEY(DEPT_CD) REFERENCES EZEN.TB_DEPT_TEMP(DEPT_CD);

-- 테이블명 변경
RENAME TB_EMP_TEMP_2 TO TB_EMP_TEMP_3;

-- 테이블의 데이터를 한번에 비움, TRUNCATE 명령 수행시 삭제한 데이터는 ROLLBACK 불가
TRUNCATE TABLE EZEN.TB_EMP_TEMP_3;

--테이블 제거
DROP TABLE EZEN.TB_EMP_TEMP_3;

-----------------------------------------------------------

--INSERT
INSERT INTO EZEN.TB_CERTI T (T.CERTI_CD, T.CERTI_NM, T.ISSUE_INSTI_NM)
VALUES ('100021', 'SQLD합격', '이젠IT');

SELECT *
FROM EZEN.TB_CERTI A
WHERE A.CERTI_CD = '100021';

--UPDATE 
UPDATE EZEN.TB_CERTI A
	SET A.ISSUE_INSTI_NM = '이젠IT온라인'
WHERE A.CERTI_CD = '100021';

--DELETE 
DELETE FROM EZEN.TB_CERTI A
WHERE A.CERTI_CD = '100021';
	
-- SELECT 

SELECT A.CERTI_CD 
	, A.CERTI_NM 
	, A.ISSUE_INSTI_NM 
FROM EZEN.TB_CERTI A
;

-- SELECT DISTINCT 
-- 컬럼 값 기준 중복을 제거한 유일한 값만 출력

SELECT DISTINCT A.ISSUE_INSTI_NM 
FROM EZEN.TB_CERTI A;

-- ALIAS 지정 (AS를 이용해 컬럼이름 지정)

SELECT A.CERTI_CD AS 자격증코드
	, A.CERTI_NM AS 자격증명
	, A.ISSUE_INSTI_NM AS 발행기관명
FROM EZEN.TB_CERTI A;


-- 합성 연산자||를 이용한 문자열 연결
SELECT
	A.CERTI_NM || '(' || A.CERTI_CD || ')' || '-' || A.ISSUE_INSTI_NM AS CERTI_INFO 
FROM EZEN.TB_CERTI A;

-- DUAL 테이블 이용 연산
SELECT ((1+1)*3) / 6 AS CALC_RESULT
FROM DUAL;


--------------------------------------------------------------
-- TCL
INSERT INTO EZEN.TB_CERTI T (T.CERTI_CD, T.CERTI_NM, T.ISSUE_INSTI_NM) VALUES
('100022', 'SQL지식보유자', '이젠IT');

SELECT *
FROM EZEN.TB_CERTI A
WHERE A.CERTI_CD = '100022'
;

UPDATE EZEN.TB_CERTI 
	SET CERTI_NM = 'SQL경험보유자'
WHERE CERTI_CD = '100022'
;

DELETE FROM EZEN.TB_CERTI tc
WHERE CERTI_CD = '100022'
;

COMMIT;

INSERT INTO EZEN.TB_CERTI T (T.CERTI_CD, T.CERTI_NM, T.ISSUE_INSTI_NM) VALUES
('100022', 'SQL지식보유자', '이젠IT');
ROLLBACK

-----------------------------------------------------------------------------------

SAVEPOINT SVPT1;		-- 세이브 포인트

INSERT INTO EZEN.TB_CERTI T (T.CERTI_CD, T.CERTI_NM, T.ISSUE_INSTI_NM) VALUES
('100022', 'SQL지식보유자', '이젠IT');

UPDATE EZEN.TB_CERTI 
	SET CERTI_NM = 'SQL경험보유자'
WHERE CERTI_CD = '100022'
;

ROLLBACK TO SVPT1;		-- 세이브 포인트(SVPT1)로 롤백 INSERT, UPDATE는 롤백

DELETE FROM EZEN.TB_CERTI tc
WHERE CERTI_CD = '100022'
;						-- 삭제실패 (데이터가 존재하지 않음)

-------------------------------------------------------------------------------

SAVEPOINT SVPT1;		-- 세이브 포인트1

INSERT INTO EZEN.TB_CERTI T (T.CERTI_CD, T.CERTI_NM, T.ISSUE_INSTI_NM) VALUES
('100022', 'SQL지식보유자', '이젠IT');

SAVEPOINT SVPT2;		-- 세이브 포인트2

UPDATE EZEN.TB_CERTI 
	SET CERTI_NM = 'SQL경험보유자'
WHERE CERTI_CD = '100022'
;

SAVEPOINT SVPT3;		-- 세이브 포인트3

DELETE FROM EZEN.TB_CERTI tc
WHERE CERTI_CD = '100022'
;

ROLLBACK TO SVPT3;

SELECT * FROM EZEN.TB_CERTI A WHERE A.CERTI_CD = '100022'
;

ROLLBACK TO SVPT2;







