-- 사원 중 수원시에 사는 사람이고 디자인팀 또는 데이터팀이면서 
-- 생년월일이 1990년대 생인 사원을 검색 

SELECT A.EMP_NO 
	, A.EMP_NAME 
	, A.SEX_CD 
	, A.BIRTH_DE 
	, A.DEPT_CD 
	, A.ADDR 
FROM TB_EMP A
WHERE A.BIRTH_DE BETWEEN '19900101' AND '19991231'	-- 1990년대 생
	AND A.DEPT_CD IN ('100004','100006')			-- 디자인팀, 데이터팀
	AND A.ADDR LIKE '%수원시%'						-- 수원시에 사는 사람
;

-- 성이 "박"씨인 직원을 출력
SELECT *
FROM TB_EMP A
WHERE A.EMP_NAME LIKE '박__'
;


-- 직속관리자번호가 NULL인 직원 조회

SELECT A.EMP_NO 
	, A.EMP_NAME 
	, A.SEX_CD 
	, A.BIRTH_DE 
	, A.DEPT_CD 
	, A.ADDR
	,NVL(A.DIRECT_MANAGER_EMP_NO, '상사 없음') DIRECT_MANAGER_EMP_NO
FROM TB_EMP A
WHERE A.DIRECT_MANAGER_EMP_NO IS NULL 
;


-- 수원시 혹은 성남시에 사는 사람을 검색
SELECT A.EMP_NO 
	, A.EMP_NAME 
	, A.SEX_CD 
	, A.BIRTH_DE 
	, A.DEPT_CD 
	, A.ADDR 
FROM TB_EMP A
WHERE A.BIRTH_DE BETWEEN '19900101' AND '19991231'	-- 1990년대 생
	AND A.DEPT_CD IN ('100004','100006')			-- 디자인팀, 데이터팀
	AND (A.ADDR LIKE '%수원시%'						-- 수원시에 사는 사람
		OR A.ADDR LIKE '%성남시%')
;



-- 수원시 혹은 성남시에 사는 사람을 제외하고 검색
SELECT A.EMP_NO 
	, A.EMP_NAME 
	, A.SEX_CD 
	, A.BIRTH_DE 
	, A.DEPT_CD 
	, A.ADDR 
FROM TB_EMP A
WHERE A.BIRTH_DE BETWEEN '19900101' AND '19991231'	-- 1990년대 생
	AND A.DEPT_CD IN ('100004','100006')			-- 디자인팀, 데이터팀
	AND NOT (A.ADDR LIKE '%수원시%'					-- 수원시에 사는 사람
		OR A.ADDR LIKE '%성남시%')
;


-- 급여지급일자가 2020년 5월인 지급 내역 중 지급 액수가 550만원 이상인 내역 출력
SELECT *
FROM TB_SAL_HIS A
WHERE PAY_DE >= '20200501'
	AND PAY_DE <= '20200531'
	AND PAY_AMT >= 5500000
;


-- 급여지급일자가 2020년 5월인 지급 내역 중 지급 액수가 550만원 미만인 내역 출력
SELECT *
FROM TB_SAL_HIS A
WHERE PAY_DE >= '20200501'
	AND PAY_DE <= '20200531'
	AND NOT PAY_AMT >= 5500000
;


-- 사원 중 수원시에 사는 사람이고 디자인팀 또는 데이터팀이면서 
-- 생년월일이 1990년대 생인 사원을 중 성별이 남자가 아닌 직원

SELECT A.EMP_NO 
	, A.EMP_NAME 
	, A.SEX_CD 
	, A.BIRTH_DE 
	, A.DEPT_CD 
	, A.ADDR 
FROM TB_EMP A
WHERE A.BIRTH_DE NOT BETWEEN '19900101' AND '19991231'	-- 1990년대 생이 아님
	AND A.DEPT_CD NOT IN ('100004','100006')			-- 디자인팀, 데이터팀이 아님
	AND A.SEX_CD <> 1									-- 성별이 남자가 아님
	AND DIRECT_MANAGER_EMP_NO IS NOT NULL	
;

-------------------------------------------------------------------------------

DROP TABLE EZEN.CHAR_COMPARE;
CREATE TABLE EZEN.CHAR_COMPARE
(	SN	CHAR(10)
	,CHAR_COMPARE_4		CHAR(4)
	,CHAR_COMPARE_6		CHAR(6)
);

INSERT INTO EZEN.CHAR_COMPARE VALUES ('1000000001', 'SQLD', 'SQLD  ');
INSERT INTO EZEN.CHAR_COMPARE VALUES ('1000000002', 'SQLD', 'SQSA  ');

SELECT 
	REPLACE (CHAR_COMPARE_4, ' ', '_') AS CHAR_COMPARE_4
	,REPLACE (CHAR_COMPARE_6, ' ', '_') AS CHAR_COMPARE_6
FROM EZEN.CHAR_COMPARE cc 
;


-- 공백만 다르다면 같다고 판단
SELECT 
	REPLACE (CHAR_COMPARE_4, ' ', '_') AS CHAR_COMPARE_4
	,REPLACE (CHAR_COMPARE_6, ' ', '_') AS CHAR_COMPARE_6
FROM EZEN.CHAR_COMPARE cc
WHERE SN = '1000000001'
	AND CHAR_COMPARE_4 = CHAR_COMPARE_6 
;

SELECT 
	REPLACE (CHAR_COMPARE_4, ' ', '_') AS CHAR_COMPARE_4
	,REPLACE (CHAR_COMPARE_6, ' ', '_') AS CHAR_COMPARE_6
FROM EZEN.CHAR_COMPARE cc
WHERE SN = '1000000001'
	AND CHAR_COMPARE_4 <> CHAR_COMPARE_6 
;


SELECT 
	REPLACE (CHAR_COMPARE_4, ' ', '_') AS CHAR_COMPARE_4
	,REPLACE (CHAR_COMPARE_6, ' ', '_') AS CHAR_COMPARE_6
FROM EZEN.CHAR_COMPARE cc
WHERE SN = '1000000002'
	AND CHAR_COMPARE_4 < CHAR_COMPARE_6 
;

------------------------------------------------------------------------

DROP TABLE EZEN.VARCHAR_COMPARE;
CREATE TABLE EZEN.VARCHAR_COMPARE
(	SN	CHAR(10)
	,VARCHAR_COMPARE_4		CHAR(4)
	,VARCHAR_COMPARE_6		VARCHAR2(6)
);

INSERT INTO EZEN.VARCHAR_COMPARE VALUES ('1000000001', 'SQLD', 'SQLD  ');
INSERT INTO EZEN.VARCHAR_COMPARE VALUES ('1000000002', 'SQLD', 'SQSA  ');

SELECT 
	REPLACE (VARCHAR_COMPARE_4, ' ', '_') AS VARCHAR_COMPARE_4
	,REPLACE (VARCHAR_COMPARE_6, ' ', '_') AS VARCHAR_COMPARE_6
FROM EZEN.VARCHAR_COMPARE vc
;

-- 결과집합 없음. 4와 6이 길이가 달라서 같지 않다고 판단
SELECT 
	REPLACE (VARCHAR_COMPARE_4, ' ', '_') AS VARCHAR_COMPARE_4
	,REPLACE (VARCHAR_COMPARE_6, ' ', '_') AS VARCHAR_COMPARE_6
FROM EZEN.VARCHAR_COMPARE vc
WHERE SN = '1000000001'
	AND VARCHAR_COMPARE_4 = VARCHAR_COMPARE_6 
;

-- SQLD까지 문자는 동일하나 공백 유무가 달라서 같지 않다고 판단
SELECT 
	REPLACE (VARCHAR_COMPARE_4, ' ', '_') AS VARCHAR_COMPARE_4
	,REPLACE (VARCHAR_COMPARE_6, ' ', '_') AS VARCHAR_COMPARE_6
FROM EZEN.VARCHAR_COMPARE vc
WHERE SN = '1000000001'
	AND VARCHAR_COMPARE_4 <> VARCHAR_COMPARE_6 
;

-- 문자유형 비교방법
-- 비교 연산자 중 한 쪽이 VARCHAR인 경우 - TRIM함수 이용
-- TRIM() : VARCHAR2 컬럼 뒤 공백 제거

SELECT 
	REPLACE (VARCHAR_COMPARE_4, ' ', '_') AS VARCHAR_COMPARE_4
	,REPLACE (VARCHAR_COMPARE_6, ' ', '_') AS VARCHAR_COMPARE_6
FROM EZEN.VARCHAR_COMPARE vc
WHERE SN = '1000000001'
	AND VARCHAR_COMPARE_4 = TRIM(VARCHAR_COMPARE_6) -- 공백 제거
;












