CREATE TABLE TB_EMP(
	EMP_NO						CHAR(10) 		NOT NULL
	,EMP_NAME					VARCHAR2(150)	NOT NULL
	,BIRTH_DE					CHAR(8)			NOT NULL
	,SEX_CD						CHAR(3)			NOT NULL
	,FINAL_EDU_SE_CD			CHAR(3)			NOT NULL
	,SAL_TRAINS_BANK_CD			CHAR(3)			NOT NULL
	,SAL_TRAINS_ACCOUNT_NO_CD	VARCHAR(20)		NOT NULL
	,DIRECT_MANAGER_EMP_NO		CHAR(20)		
	,ADDR						VARCHAR2(20)	NOT NULL
	,TEL_NO						VARCHAR2(20)	NOT NULL
	,DEPT_CD					CHAR(20)		NOT NULL
	,PRIMARY KEY(EMP_NO)
	,FOREIGN KEY(DEPT_CD) 				REFERENCES TB_DEPT(DEPT_CD)
	,FOREIGN KEY(DIRECT_MANAGER_EMP_NO) REFERENCES TB_EMP(EMP_NO)
);


CREATE TABLE TB_DEPT (
	DEPT_CD						CHAR(6) 		NOT NULL
	,DEPT_NM					VARCHAR2(150)	NOT NULL
	,UPPER_DEPT_CD				CHAR(6)			
	,PRIMARY KEY(DEPT_CD)
	,FOREIGN KEY(UPPER_DEPT_CD) REFERENCES TB_DEPT(DEPT_CD)
);


CREATE TABLE TB_EMP_CERTI (
	EMP_NO		CHAR(10)	NOT NULL
	,CERTI_SN	CHAR(3) 	NOT NULL
	,CERTI_CD	CHAR(6)	 	NOT NULL
	,ACQU_DE	CHAR(8)		NOT NULL
	,PRIMARY KEY (EMP_NO)
	,FOREIGN KEY(EMP_NO) 	REFERENCES TB_EMP(EMP_NO)
	,FOREIGN KEY(CERTI_CD) 	REFERENCES TB_EMP_CERTI_1(CERTI_CD)
);


CREATE TABLE TB_EMP_CERTI_1 (
	CERTI_CD		CHAR(6)			NOT NULL
	,CERTI_NM		VARCHAR2(150)	NOT NULL
	,ISSUE_INSTI_NM	VARCHAR2(150)	NOT NULL
	,PRIMARY KEY (CERTI_CD)
);


CREATE TABLE TB_SAL_HIS (
	SAL_HIS_NO		CHAR(14)	NOT NULL
	,PAY_DE			CHAR(8)		NOT NULL
	,PAY_AMT		NUMBER(15)	NOT NULL
	,EMP_NO			CHAR(10)	NOT NULL
	,PRIMARY KEY (SAL_HIS_NO)
	,FOREIGN KEY(EMP_NO) REFERENCES TB_EMP(EMP_NO)
);


CREATE TABLE TB_HIS_DTL(
	SAL_HIS_NO		CHAR(14)	NOT NULL
	,DTL_SN			CHAR(3)		NOT NULL
	,PAY_DTL_AMT	CHAR(15)	NOT NULL
	,SAL_CD			CHAR(6)		NOT NULL
	,PRIMARY KEY (SAL_HIS_NO)
	,FOREIGN KEY(SAL_HIS_NO) 	REFERENCES TB_SAL_HIS(SAL_HIS_NO)
	,FOREIGN KEY(SAL_CD) 		REFERENCES TB_SAL(SAL_CD)
);



CREATE TABLE TB_SAL(
	SAL_CD		CHAR(6)			NOT NULL
	,SAL_NM		VARCHAR2(150)	NOT NULL
	,PRIMARY KEY (SAL_CD)
);

